.github/workflows/acms.yml
README.md
acms/acms.yml
tests/packages_alter.yml
tests/unit/CliTest.php

Updated name in README,CLI and CLI Test

ACMS-1280: Updating name to Acquia CMS Enterprise Low-code.

---

.github/workflows/acms.yml
README.md
tests/packages_alter.yml

Updating readme 
Adding ORCA Job environment for static code analysis

ACMS-1288: Update readme and github workflow for starterkit.

---

acms/acms.yml
config/services.yml
src/Commands/AcmsInstallCommand.php
src/Helpers/InstallerQuestions.php
src/Helpers/Task/InstallTask.php
src/Helpers/Task/Steps/InitNextjsApp.php
tests/unit/CliTest.php
tests/unit/Helpers/InstallerQuestionsTest.php

ACMS-1314: Headless starter kit - Ask question to use Next.js in headless starter kit wizard

---

acms/acms.yml
src/Cli.php
tests/unit/CliTest.php

ACMS-1369: Remove module version constraint.

---

src/Helpers/Task/Steps/InitNextjsApp.php

Reverting the changes for auto-checking the checkbox while installation of starterkit and opt for nextjs

ACMS-1368: Reverting the earlier changes made for auto checkbox checked.

---

.github/workflows/acms.yml
tests/packages_alter.yml

Unpin ORCA version and use the latest release.

ACMS-1287: Unpin the ORCA version, so to use the latest release.

---

src/Helpers/Task/InstallTask.php
src/Helpers/Task/SharedFactory.php
src/Helpers/Task/Steps/SiteInstall.php
src/Helpers/Utility.php
tests/unit/Helpers/UtilityTest.php

ACMS-1393: Added password generation logic.

---

.github/workflows/acms.yml
src/Helpers/Task/Steps/DownloadModules.php

Removed ACMS DAM vcs path.
Now ACMS starterkit should download ACMS DAM module from Drupal.Org

ACMS-000: Remove ACMS DAM module vcs path.

---

.github/workflows/acms.yml
acms/acms.yml
config/services.yml
src/Cli.php
src/Commands/AcmsBuildCommand.php
src/Commands/AcmsInstallCommand.php
src/Commands/SiteInstallCommand.php
src/Helpers/Task/InstallTask.php
src/Helpers/Task/SharedFactory.php
src/Helpers/Task/Steps/AskQuestions.php
src/Helpers/Task/Steps/EnableModules.php
src/Helpers/Task/Steps/EnableThemes.php
tests/unit/CliTest.php
tests/unit/Helpers/InstallerQuestionsTest.php

Fixes: ACMS-1589
Testing steps: follow from ACMS-1589.

ACMS-1589: Split acms acms:install command update acms site:install command, install tasks

---

.github/dependabot.yml

Enable Dependabot in Acquia CMS Starterkit.

ACMS-1518: Enable Dependabot in Acquia CMS Starterkit.

---

src/Helpers/Task/Steps/DownloadModules.php

ACMS-1422: Fix Explore with Swagger UI headless issue.

---

.github/workflows/acms.yml

ACMS-1573: Add Cron in CI to run with Acquia CMS Starterkit.

---

composer.lock

Fix vulnerability on acquia/acquia-cms-starterkit's default branch (1 moderate).
more info: https://github.com/acquia/acquia-cms-starterkit/security/dependabot/2

ACMS-1573: update symfony/http-kernel to latest.

---

.github/workflows/acms.yml

ACMS-1573: Add logic to display log installation information in CI.

---

.github/workflows/acms.yml

ACMS-1433: Add CI/CD tests for Headless starter kit with NextJS site.

---

.github/workflows/acms.yml

ACMS-644: add GDPR question in CI.

---

composer.json
composer.lock

Stceman released 0.12.1 https://github.com/stecman/symfony-console-completion/issues/95

ACMS-1857: Removing stecman patch as its released.

---

src/Helpers/Task/Steps/SiteInstall.php

**Motivation**
Fixes #ACMS-1885
Fix site install regression issue introduced in 1.1.4 version.
NA

ACMS-1885: Fix site install regression issue introduced in 1.1.4 version.

---

src/Cli.php

**Motivation**
Fixes #ACMS-1137
Provide way to customer to build own starterkit.
NA
Follow from ticket.

ACMS-1137: Build own Acquia CMS Starter Kit.

---

src/Helpers/Process/Commands/CommandBase.php
src/Helpers/Process/Commands/Drush.php
src/Helpers/Task/Steps/DownloadModules.php

**Motivation**
Fixes #ACMS-1903
Use local executable for drush and fallback to global.
NA
Follow from ticket.

ACMS-1903: Use local executable for drush and fallback to global.

---

src/Commands/SiteInstallCommand.php

**Motivation**
Fixes ACMS-1386
Capturing install time.

ACMS-1386: Storing install time in seconds format.

---

.github/workflows/acms.yml
acms/acms.yml
src/Cli.php
src/Commands/AcmsBuildCommand.php
src/Commands/AcmsInstallCommand.php
src/Commands/SiteInstallCommand.php
src/Helpers/InstallerQuestions.php
src/Helpers/Parsers/PHPParser.php
src/Helpers/Task/BuildTask.php
src/Helpers/Task/InstallTask.php
src/Helpers/Task/Steps/AskQuestions.php
src/Helpers/Task/Steps/EnableModules.php
src/Helpers/Task/Steps/SiteInstall.php
src/Helpers/Traits/UserInputTrait.php
tests/unit/CliTest.php
tests/unit/Helpers/InstallerQuestionsTest.php
tests/unit/Helpers/Parsers/PHPParserTest.php
tests/unit/Helpers/Traits/UserInputTraitTest.php

**Motivation**
Fixes ACMS-1632

ACMS-1632: Making question keys into generic format for all.

---

acms/acms.yml
src/Cli.php
src/Commands/AcmsBuildCommand.php
src/Commands/AcmsInstallCommand.php
src/Commands/SiteInstallCommand.php
src/Helpers/InstallerQuestions.php
src/Helpers/Task/BuildTask.php
src/Helpers/Task/InstallTask.php
tests/unit/CliTest.php
tests/unit/Helpers/InstallerQuestionsTest.php

**Motivation**
Fixes ACMS-1900
Adding Help Text in acms.yml to relate as the command options description.
Questions will be asked if user doesn't include that option in script/command.

ACMS-1900: Flexiblity of command options.

---

.github/workflows/acms.yml

**Motivation**
Fixes ACMS-3340
Added a patch to support D9 in CI

ACMS-3340: Fix failing CI.

---

tests/packages_alter.yml

ACMS-000: Fix failing CI.

---

src/Helpers/Task/InstallTask.php

ACMS-3456: Update logic to enable theme.

---

acms/acms.yml
tests/unit/CliTest.php

**Motivation**
Fixes #[ACMS-3477](https://acquia.atlassian.net/browse/ACMS-3477)
Add sitestudio_gin module in ACMS.
Follow from ticket.

ACMS-4377: Add sitestudio_gin module in ACMS.

---

.github/dependabot.yml

ACMS-3456: Update dependabot for npm package upgrade dependencies.

---

tests/packages_alter.yml

**Motivation**
Fixes 3362
Validating support of contenthub 3.3.x and CI should pass.

ACMS-3362: Updating packages alter for starterkit.

---

.github/workflows/acms.yml

**Motivation**
Fixed the failing CI for Drupal Core 10.1.x.
Update workflow.yml.
N/A
CI should pass.

ACMS-000: Fixed the failing CI.

---

.github/dependabot.yml

ACMS-000: Enable dependabot for npm packages.

---

composer.json
composer.lock

**Motivation**
Fix composer vulnerability.
Update composer to ^2.7.0(latest version).
NA

ACMS-3660: Fix composer vulnerability.

---

tests/functional/package-lock.json
tests/functional/package.json

**Motivation**
Fix cypress/request vulnerability.
Fix Server-Side Request Forgery in Request by updating cypress/request 3.0.1(latest version).
NA

ACMS-3660: Fix cypress/request vulnerability.

---

src/Helpers/Task/BuildTask.php

ACMS-000: Fix missing starterkit updation logic.

---

src/Cli.php
src/Helpers/Task/InstallTask.php
tests/unit/CliTest.php

**Motivation**
Fixes ACMS-3705
Enabling themes before modules.

ACMS-3705: Enabling themes first before modules.

---

.github/workflows/acms.yml

**Motivation**
Fixes #[ACMS-3593](https://acquia.atlassian.net/browse/ACMS-3593)
Update actions to v4.
NA
Verify CI.

ACMS-3593: Update actions to v4.

---

README.md

**Motivation**
Fixes ACMS-3502
Updated readme to include php memory limit 256M

ACMS-3502: Update README.md

---

tests/unit/CliTest.php
tests/unit/Helpers/InstallerQuestionsTest.php
tests/unit/Helpers/Parsers/JsonParserTest.php
tests/unit/Helpers/Parsers/PHPParserTest.php
tests/unit/Helpers/Process/GenericCommandTest.php
tests/unit/Helpers/Traits/StatusMessageTraitTest.php
tests/unit/Helpers/Traits/UserInputTraitTest.php
tests/unit/Helpers/UtilityTest.php

**Motivation**
Fixes ACMS-3641
Adding static to dataproviders in phpunit.

ACMS-3641: Adding static to the data providers for phpunit cases.

---

composer.lock
phpunit.xml.dist

**Motivation**
Fixes ACMS-3641
Updating phpunit.xml.dist file

ACMS-3641: Updating phpunit xml.dist file.

---

.github/workflows/acms.yml
composer.json
composer.lock
src/Http/Client/Github/AcquiaRecommendedClient.php

**Motivation**
Fixes #[ACMS-3963](https://acquia.atlassian.net/browse/ACMS-3963)
Drupal 11 compatibility of Acquia CMS Starterkit.
NA
Follow from ticket.

ACMS-3963: D11 compatibility Acquia CMS Starterkit.
